### ISSUE TITLE
project ESP32-OTA-Webserver missing

### ISSUE THREAD

**Issue by Benedito821** [versamodule/ESP32-OTA-Commandline#3]
Hello, @versamodule ! Has the project ESP32-OTA-Webserver been deleted?

**Comment by versamodule** [comment]
Yes. I have crated a new one, and will be uploading that in the next few weeks. 

![Screenshot 2021-08-28 084402](https://user-images.githubusercontent.com/6456652/131219921-7a45733c-050b-4863-9fbc-2cae0d1a00e2.png)

**Comment by Benedito821** [comment]
Okay, many thanks!
